name: Publish NuGet Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x.x' # Specify the .NET version you are using

      - name: Clean
        run: dotnet clean

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity detailed

      - name: Publish test results
        uses: actions/upload-artifact@v4
        with:
            name: Test Results
            path: '**/*.trx'
        
      - name: Pack
        run: dotnet pack --configuration Release --no-build --output ./nupkg

      - name: Publish to GitHub Packages
        run: dotnet nuget push ./nupkg/*.nupkg --source "github" --api-key ${{ secrets.GITHUB_TOKEN }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
